// Generated by CoffeeScript 2.5.1
(function() {
  var fs;

  fs = require('fs');

  exports.createPackageFile = function() {
    var ref;
    this.PackageSource = ((ref = this.api.server) != null ? ref.dependencies : void 0) ? JSON.stringify({
      name: `${this.name}.server`,
      dependencies: this.api.server.dependencies
    }) : JSON.stringify({
      name: `${this.name}.server`
    });
    return this.createPackageFile = function() {
      return fs.writeFileSync(`${this.dir}/package.json`, this.PackageSource);
    };
  };

}).call(this);
