// Generated by CoffeeScript 2.5.1
(function() {
  var fs;

  fs = require('fs');

  exports.createPackageFile = function() {
    var dependencies, ref;
    this.PackageSource = (dependencies = (ref = this.api.server) != null ? ref.dependencies : void 0) ? JSON.stringify({name: this.name, dependencies}) : JSON.stringify({name: this.name});
    return this.createPackageFile = function() {
      return fs.writeFileSync(`${this.dir}/package.json`, this.PackageSource);
    };
  };

}).call(this);
