// Generated by CoffeeScript 2.5.1
(function() {
  var fs;

  fs = require('fs');

  exports.createPackageFile = function() {
    var dependencies, ref;
    this.PackageSource = (dependencies = (ref = this.api.server) != null ? ref.dependencies : void 0) ? JSON.stringify({name: this.name, dependencies}) : JSON.stringify({name: this.name});
    return this.createPackageFile = function() {
      var file, source;
      file = `${this.dir}/package.json`;
      if (fs.existsSync(file)) {
        source = fs.readFileSync(file, 'utf-8');
        if (source === this.PackageSource) { // early to not trigger 'npm install' unless necessary
          return;
        }
      }
      return fs.writeFileSync(file, this.PackageSource);
    };
  };

}).call(this);
