// Generated by CoffeeScript 2.5.1
(function() {
  var Client, Server, YAML, ensureDirExists, fs, getSources, path, printHelp;

  fs = require('fs');

  path = require('path');

  YAML = require('yaml');

  require('./ext');

  ({Client} = require('./client'));

  ({Server} = require('./server'));

  ({ensureDirExists} = require('./util'));

  exports.run = function() {
    var _agn, _node, command, dir, sources;
    [_node, _agn, command] = process.argv;
    switch (command) {
      case 'build':
        dir = `${process.cwd()}/build`;
        ensureDirExists(dir);
        sources = getSources();
        Server(sources)(`${dir}/server`);
        return Client(sources)(`${dir}/client`);
      default:
        return printHelp();
    }
  };

  getSources = function() {
    var api, cwd, functions, i, key, len, name, ref;
    cwd = process.cwd();
    name = path.basename(cwd);
    api = YAML.parse(fs.readFileSync(`${cwd}/api.yml`, 'utf-8'));
    functions = {};
    ref = Object.keys(api.functions);
    for (i = 0, len = ref.length; i < len; i++) {
      key = ref[i];
      functions[key] = fs.readFileSync(`${cwd}/functions/${key}.coffee`, 'utf-8');
    }
    return {name, api, functions};
  };

  printHelp = function() {
    return console.log('printHelp');
  };

}).call(this);
