// Generated by CoffeeScript 2.5.1
(function() {
  var YAML, createClient, createServer, fs, getSources;

  fs = require('fs');

  YAML = require('yaml');

  require('./ext');

  ({createClient} = require('./client'));

  ({createServer} = require('./server'));

  exports.run = function() {
    var dir, sources;
    dir = `${process.cwd()}/build`;
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir);
    }
    sources = getSources();
    return createClient(sources);
  };

  // createServer sources
  getSources = function() {
    var api, build, cwd, functions, i, len, name, ref;
    cwd = process.cwd();
    build = YAML.parse(fs.readFileSync(`${cwd}/build.yml`, 'utf-8'));
    api = YAML.parse(fs.readFileSync(`${cwd}/api.yml`, 'utf-8'));
    functions = {};
    ref = Object.keys(api.functions);
    for (i = 0, len = ref.length; i < len; i++) {
      name = ref[i];
      functions[name] = fs.readFileSync(`${cwd}/functions/${name}.coffee`, 'utf-8');
    }
    return {build, api, functions};
  };

}).call(this);
