// Generated by CoffeeScript 2.5.1
(function() {
  var Api, Creator, coffee, fs;

  fs = require('fs');

  coffee = require('coffeescript');

  ({Creator} = require('./creator'));

  ({Api} = require('./client/api'));

  exports.Client = Creator({
    init: {
      name: function() {
        return this;
      },
      api: Api
    },
    once: function() {
      this.PackageSource = JSON.stringify({
        name: `${this.name}.client`,
        version: '0.0.0',
        dependencies: {
          axios: '*'
        }
      });
      this.createPackageFile = function() {
        return fs.writeFileSync(`${this.dir}/package.json`, this.PackageSource);
      };
      this.CoffeeSource = this.api.createCoffeeSource();
      return this.createIndexFile = function() {
        fs.writeFileSync(`${this.dir}/index.coffee`, this.CoffeeSource);
        return fs.writeFileSync(`${this.dir}/index.js`, coffee.compile(this.CoffeeSource));
      };
    },
    call: function(dir) {
      this.inside(dir, function() {
        this.createPackageFile();
        return this.createIndexFile();
      });
      return console.log(`Building the client at ${dir}.`);
    }
  });

}).call(this);
