// Generated by CoffeeScript 2.5.1
(function() {
  var Validate, badResponse, badValue, coffee, createCoffeeFile, createFunctionWithInput, createFunctionWithoutInput, createIfs, createJSFile, createPackageFile, createRootDirectory, create_validateInputOf, create_validateOutputOf, fs, root;

  fs = require('fs');

  coffee = require('coffeescript');

  ({Validate} = require('./validator'));

  root = '';

  createIfs = function() {};

  exports.createClient = function(sources) {
    createIfs = Validate(sources.api.types);
    createRootDirectory();
    createPackageFile(sources.build);
    createCoffeeFile(sources);
    return createJSFile();
  };

  createRootDirectory = function() {
    root = `${process.cwd()}/build/client`;
    return fs.mkdirSync(root);
  };

  createPackageFile = function({name}) {
    var spec;
    spec = {
      name: `${name}.client`,
      dependencies: {
        axios: '*'
      }
    };
    return fs.writeFileSync(`${root}/package.json`, JSON.stringify(spec));
  };

  createCoffeeFile = function({build, api}) {
    var functions;
    functions = (Object.keys(api.functions)).map(function(fn) {
      if (api.functions[fn].in) {
        return createFunctionWithInput(fn, api);
      } else {
        return createFunctionWithoutInput(fn, api);
      }
    });
    return fs.writeFileSync(`${root}/index.coffee`, `axios = require 'axios'

address = '${build.address}'
HTTP = axios

${functions.join("\n\n")}`);
  };

  createJSFile = function() {
    var source;
    source = coffee.compile(fs.readFileSync(`${root}/index.coffee`, 'utf-8'));
    return fs.writeFileSync(`${root}/index.js`, source);
  };

  badResponse = 'the server responded with the status #{response.status}';

  createFunctionWithInput = function(name, api) {
    return `${create_validateInputOf(name, api.functions[name].in)}

${create_validateOutputOf(name, api.functions[name].out)}

exports.${name} = (input) ->
  validateInputOf_${name} input

  response = await HTTP.post address,
    fn: '${name}'
    in: input

  if response.status is 200
    output = response.data.out
    validateOutputOf_${name} output
    output
  else
    throw "${name}: ${badResponse}."`;
  };

  createFunctionWithoutInput = function(name, api) {
    return `${create_validateOutputOf(name, api.functions[name].out)}

exports.${name} = ->
  response = await HTTP.post address, fn: '${name}'

  if response.status is 200
    output = response.data.out
    validateOutputOf_${name} output
    output
  else
    throw "${name}: ${badResponse}."`;
  };

  badValue = '#{value}:#{typeof value} was received. Error: #{error.toString()}';

  create_validateInputOf = function(fn, type) {
    return `validateInputOf_${fn} = (value) ->
  try
    throw "no value" unless value?

${createIfs({type}).indent({
      number: 4
    })}

  catch error
    throw new TypeError "${fn} requires ${type} output, but ${badValue}."`;
  };

  create_validateOutputOf = function(fn, type) {
    return `validateOutputOf_${fn} = (value) ->
  try
    throw "no value" unless value?

${createIfs({type}).indent({
      number: 4
    })}

  catch error
    throw new TypeError "${fn} requires ${type} output, but ${badValue}."`;
  };

}).call(this);
