// Generated by CoffeeScript 2.5.1
(function() {
  var ensureDirExists, fun, state;

  ({fun} = require('./fun'));

  ({ensureDirExists} = require('./util'));

  state = {
    inside: function(dir, fn) {
      var copy;
      ensureDirExists(dir);
      copy = {...this};
      copy.dir = dir;
      return fn.call(copy);
    },
    embed: function(fns) {
      var fn, i, len, results;
      results = [];
      for (i = 0, len = fns.length; i < len; i++) {
        fn = fns[i];
        results.push(fn.call(this));
      }
      return results;
    }
  };

  exports.Creator = function(input) {
    return fun({...input, state});
  };

}).call(this);
