// Generated by CoffeeScript 2.5.1
(function() {
  String.prototype.indent = function(options) {
    var indentation, number;
    number = (options != null ? options.number : void 0) || 2;
    indentation = ' '.repeat(number);
    return this.split("\n").map(function(line) {
      return `${indentation}${line}`;
    }).join("\n");
  };

  //.slice(0, -number)

}).call(this);
