// Generated by CoffeeScript 2.5.1
(function() {
  exports.fun = function({init, once, call}) {
    return function(input) {
      var fn, key, state;
      state = {};
      for (key in init) {
        fn = init[key];
        state[key] = fn.call(input[key]);
      }
      if (once) {
        once.call(state);
      }
      return call.bind(state);
    };
  };

}).call(this);
