// Generated by CoffeeScript 2.5.1
(function() {
  var ensureDirExists, fun, state;

  ({fun} = require('./fun'));

  ({ensureDirExists} = require('./util'));

  state = {
    inside: function(dir, fn) {
      var copy;
      ensureDirExists(dir);
      copy = {...this};
      copy.dir = dir;
      return fn.call(copy);
    }
  };

  exports.Generator = function(input) {
    return fun({...input, state});
  };

}).call(this);
