// Generated by CoffeeScript 2.5.1
(function() {
  var Creator, auth, createFnFiles, createMainFile, parseEntities;

  ({Creator} = require('./creator'));

  ({createMainFile} = require('./server/main'));

  ({parseEntities, createFnFiles} = require('./server/functions'));

  ({auth} = require('./server/auth'));

  exports.Server = Creator({
    init: {
      name: function() {
        return this;
      },
      api: function() {
        return this;
      },
      functions: parseEntities,
      auth: auth
    },
    once: function() {
      return this.embed([createMainFile, createFnFiles]);
    },
    call: function(dir) {
      this.inside(dir, function() {
        this.createMainFile();
        return this.createFnFiles();
      });
      return console.log(`Building the server at ${dir}.`);
    }
  });

}).call(this);
