// Generated by CoffeeScript 2.5.1
(function() {
  var Api, Functions, coffee, ensureDirExists, fs, fun;

  fs = require('fs');

  coffee = require('coffeescript');

  ({fun} = require('./fun'));

  ({ensureDirExists} = require('./util'));

  Api = function() {
    var functions, types;
    ({functions, types} = this);
    this.whenCases = (Object.keys(functions)).map(function(fn) {
      var body, pre;
      pre = `when '${fn}'`;
      body = functions[fn].in ? `  await require('./${fn}.js')(message.in)` : `  await require('./${fn}.js')()`;
      return `${pre}\n${body}`;
    }).join("\n");
    return this;
  };

  Functions = function() {};

  exports.Server = fun({
    init: {
      name: function() {
        return this;
      },
      api: Api,
      functions: Functions
    },
    once: function() {
      var catchBadRequest, listener, requestEnd;
      this.PackageContent = JSON.stringify({
        name: `${this.name}.server`
      });
      this.createPackageFile = function() {
        return fs.writeFileSync(`${this.dir}/package.json`, this.PackageContent);
      };
      catchBadRequest = `catch error
  console.log error
  response.statusCode = 400
  response.end()`;
      requestEnd = () => {
        return `try
  message = JSON.parse data

  out = switch message.fn
${this.api.whenCases.indent({
          number: 4
        })}
  
  response.setHeader 'Content-Type', 'application/json'
  response.statusCode = 200
  response.end JSON.stringify out: out
${catchBadRequest}`;
      };
      listener = `listener = (request, response) ->
  try
    unless request.method in ['POST', 'OPTIONS']
      throw 'bad request'
    response.setHeader 'Access-Control-Allow-Origin', '*'

    switch request.method
      when 'OPTIONS'
        response.setHeader 'Access-Control-Allow-Methods', 'POST, OPTIONS'
        response.setHeader 'Access-Control-Allow-Headers', 'Authorization, Content-Type'
        response.setHeader 'Access-Control-Max-Age', '86400'
        response.end()
      when 'POST'
        unless request.headers['content-type']?.startsWith 'application/json'
          throw 'bad request'

        data = ''
        request.on 'data', (chunk) ->
          data += chunk
        request.on 'end', ->
${requestEnd().indent({
        number: 10
      })}
${catchBadRequest.indent({
        number: 2
      })}`;
      this.CoffeeContent = `http = require 'http'

${listener}

server = http.createServer listener

PORT = process.env.PORT or 8080
server.listen PORT, ->
  console.log "The server is listening."`;
      this.createCoffeeFile = function() {
        return fs.writeFileSync(`${this.dir}/server.coffee`, this.CoffeeContent);
      };
      this.createJSFile = function() {
        return fs.writeFileSync(`${this.dir}/server.js`, coffee.compile(this.CoffeeContent));
      };
      return this.inside = function(dir, fn) {
        var copy;
        ensureDirExists(dir);
        copy = Object.assign({}, this);
        copy.dir = dir;
        return fn.call(copy);
      };
    },
    call: function({dir}) {
      return this.inside(dir, function() {
        this.createPackageFile();
        this.createCoffeeFile();
        return this.createJSFile();
      });
    }
  });

}).call(this);
