// Generated by CoffeeScript 2.5.1
(function() {
  var deepEqual, fs, isEqual;

  fs = require('fs');

  exports.ensureDirExists = function(dir) {
    if (!fs.existsSync(dir)) {
      return fs.mkdirSync(dir);
    }
  };

  ({deepEqual} = require('assert').strict);

  isEqual = function(a, b) {
    var error;
    try {
      deepEqual(a, b);
      return true;
    } catch (error1) {
      error = error1;
      if (error.name === 'AssertionError') {
        return false;
      } else {
        throw error;
      }
    }
  };

  exports.isNotEqual = function(a, b) {
    return !(isEqual(a, b));
  };

}).call(this);
